language: node_js

node_js: "11"

cache:
  directories:
    - node_modules

before_install:
  - npm i -g yarn

install:
  - yarn

before_script:
  - yarn build

jobs:
  include:
    - stage: test
      script:
        - yarn verify
        - codecov

branches:
  only:
    - master
    - develop
