name: Publish

on:
  push:
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']
    steps:
    - uses: actions/checkout@v1
    - name: Checkout Hack (Push Ability)
      run: |
        git remote -v
        git checkout "${GITHUB_REF:11}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Build packages
      run: yarn compile
    - name: Create release & publish package
      run: |
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        yarn release:publish --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
