name: Pull Request

on:
  pull_request:
    branches:
    - master
    - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: { node-version: 12 }
    - name: Yarn Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn
    - run: yarn audit:ci
    - run: yarn compile
    - name: Upload built packages
      uses: actions/upload-artifact@v2-preview
      with: { name: dist, path: ./packages/*/dist }
  test:
    name: Test
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Yarn Cache
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn
    - uses: actions/download-artifact@v1 # TODO: Change to v2 when gzip is fixed
      with: { name: dist, path: ./packages/ }
    - run: yarn lint
    - run: cat ./packages/http/dist/types/index.d.ts
      if: matrix.os == 'ubuntu-latest'
    - run: yarn test
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.node_version
      uses: codecov/codecov-action@v1
