name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Prepare environment
      run: yarn
    - name: Build packages
      run: yarn compile
    - name: Release
      run: yarn release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
