name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['12']
    steps:
    - uses: actions/checkout@v1
    - name: Prepare repository (resolves detached HEAD issue)
      run: git checkout "${GITHUB_REF:11}"
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Create release & publish package
      run: yarn release --yes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
